### PR TITLE
Added new config option to relocate Xauthority

### PR DESCRIPTION
**Pull request by linuxrrze**
Usually the .Xauthority files are created in the users home directory.
However in some environments (e.g. NFS-based home directories, secured by Kerberos) the root user is not allowed to create those files. This options allows to relocate them.
Sample config was also added to config.ini

### CODE REVIEW

**Comment by bmiklautz** [comment]
@linuxrrze sorry the PR must have slipped through my radar.

The xauthority path looks and increasing the maximum resolution looks good.

Regarding openh264 that was done this way intentionally. ogon is compiled against a specific version of openh264 that is loaded once ogon is started. The binaries can be fetched during runtime (have a look to https://github.com/ogon-project/ogon/blob/master/misc/ogon-get-openh264-codec.in). If a self compiled version of openh264 license costs might arise.

**Comment by bmiklautz** [comment]
@linuxrrze I'd suggest you create a new PR with the xauth/resolution part only. 

For openh264 we should definitely update to a more recent version but this requires more update(s).

Thank you for your effort.

**Comment by hardening** [comment]
@linuxrrze yeah it would be nice if you could split the Xauthority/resolution part from the rest in a separate PR

**Comment by linuxrrze** [comment]
I thought I already did so ...
However I can open a new PR for the Xauthority stuff as I'm about to push some other things anyway.

**Comment by nfedera** [comment]
Superseeded by #25 and #26

**Pull request closed without merging**
