### PR TITLE
protocols, rdp-server: add reconnection capabilities on the rdp server

### PR DESCRIPTION
**Pull request by hardening**
Add the capability to automatically reconnect using a reconnection cookie. To achieve that some messages have been added so that the sessionManager can notify the sessionId and reconnectCookie to the RDP peer. The ICP protocol also has a new message to reconnect instead of logging in.

Note: the sessionManager part is not implemented for now, it would need to

* implement the ReconnectUser callback;
* send the reconnect infos (cookie and sessionId) once logged on, and periodicly refresh it (cookie is supposed to be renew each hour according to the specs)

Note: https://github.com/FreeRDP/FreeRDP/pull/4980 is highly recommanded on FreeRDP

### CODE REVIEW

**Comment by bmiklautz** [comment]
@hardening as the session-manager part is not yet implemented how did you do your tests (that I can test the PR as well)

**Comment by hardening** [comment]
I used my own session manager, topka, written in python. I'm actually working on it.

**Comment by hardening** [comment]
I've added a new message so that the sessionManager can grab connection statistics (in/out bytes and packets) from ogoin-rdp-server.

**Comment by hardening** [comment]
I will re-push it later on.

**Pull request closed without merging**
