### PR TITLE
Fixed build against freerdp 2.3.0

### PR DESCRIPTION
**Pull request by linuxrrze**
Fixing build against new freerdp 2.3.0
Thanks to akallabeth for providing the necessary information!

### CODE REVIEW

**Review by hardening — APPROVED** [review]

**Comment by bmiklautz** [comment]
This would break the build against the tested (but old) FreeRDP in the ogon-project. I'd like to update ogon-freerdp before merging this in. 
Thank you @linuxrrze

**Comment by akallabeth** [comment]
@bmiklautz are you sure? The correct error code should also be in the old version, it was just a mixup with the connect error codes previously used by the mac client

Am 15. April 2021 16:22:22 UTC schrieb Bernhard Miklautz ***@***.***>:

**Comment by bmiklautz** [comment]
@akallabeth true that. Thanks for pointing that out.

**Comment by bmiklautz** [comment]
ogon-freerdp should be updated any way ;)

**Pull request merged**
