### PR TITLE
Updated debian package

### PR DESCRIPTION
**Pull request by akallabeth**
1. Updated debian package for 1.0 release (names of libraries, ...)
1. Updated thrift dependency (prefer shared library)
1. Require c++ 17, replaced `boost::shared_ptr` et al with `std::shared_ptr`
1. Fixed compiler warnings (invalid flags for C++)

### CODE REVIEW

**Comment by hardening** [comment]
File `ogon_ffmpeg.c` looks like a bogus adding (a copy of `openh264.c`)

**Comment by akallabeth** [comment]
@hardening true, did start playing around with backends, but forgot to remove it.

**Comment by akallabeth** [comment]
@hardening a simple `dpkg-buildpackage` now works for my `debian bullseye` machine to install ogon.

**Comment by bmiklautz** [comment]
@akallabeth nice work! THANKs
@hardening with the updated thrift version initial parallell builds work fine :)

**Pull request merged**
