### PR TITLE
core, rdp-server, session-manager: add a call to retrieve a list of properties from the SM

### PR DESCRIPTION
**Pull request by hardening**
The new PropertyBulk message allows the RDP server to retrieve most of the properties it
needs from the session manager in just one call. This fasten the connection process.

I'm wondering if I must implement a compatibility layer when a recent ogon RDP server runs with an older session manager. In this case I could emulate the bulk behaviour with serialized queries. Anyway I think this case never happens, any opinion on this ?

### CODE REVIEW

**Comment by bmiklautz** [comment]
@hardening the combination of a session manager and a rdp server with a different version is unlikely at the moment. However the version number was intended that new behaviour can be en- or disabled.

**Comment by bmiklautz** [comment]
@hardening if this is wip you could convert the PR to a draft.

**Comment by hardening** [comment]
Well I set WIP more for the question about backward compatibility

**Comment by hardening** [comment]
Ok, backward compatibility implemented. So this PR also contains what is needed for further developments that may change the protocol and will do backward compatibility.

**Comment by hardening** [comment]
anybody to review and merge this one ?

**Comment by hardening** [comment]
Any reviewer for this PR ?

**Comment by bmiklautz** [comment]
@hardening sorry for the really really long delay! - Will review and test today. 
Could you rebase this PR to the latest master?

**Comment by bmiklautz** [comment]
@hardening this is a really nice addition! Very well done. Thank you.

**Comment by hardening** [comment]
rebase done

**Pull request merged**
