### PR TITLE
rdp-server: add a command line option to set the log level

### PR DESCRIPTION
**Pull request by hardening**

### CODE REVIEW

**Comment by nfedera** [comment]
LGTM, would you add this also to `session-manager/main.cpp` so that both main services are in sync in this regard?

**Comment by hardening** [comment]
> LGTM, would you add this also to `session-manager/main.cpp` so that both main services are in sync in this regard?

We have a deal.

**Comment by hardening** [comment]
@nfedera done

**Comment by hardening** [comment]
Anybody to merge this one ?

**Pull request merged**
